[package]
name = "musitseq"
version = "0.1.0"
authors = ["pdelrieu"]

[dependencies.comm]
git = "https://github.com/mahkoh/comm"

#[dependencies.portmidi]
#path = '../temp/portmidi-rs'

[dependencies]
time = "0.1"
midi = "*"
portmidi = "*"
#comm = "*"

